[20-Nov-2024 16:14:18 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:18:19 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:24:48 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:39:27 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:42:22 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:45:56 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:47:57 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:50:23 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:52:28 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:53:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:56:45 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 16:58:11 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 17:03:48 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 17:14:17 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 17:16:48 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 17:17:10 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 17:27:55 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 19:18:46 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 19:20:12 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 19:21:02 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 19:21:26 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 21:35:42 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 23:12:32 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 23:35:55 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 23:40:46 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 23:41:40 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 23:57:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 23:57:14 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[20-Nov-2024 23:57:19 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[21-Nov-2024 02:02:02 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
[21-Nov-2024 02:02:19 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:253
Stack trace:
#0 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/foinfo/pa...', 253, 5)
#1 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#2 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#4 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#6 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(341): include('/home/foinfo/pa...')
#8 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(877): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(851): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(826): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(805): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(704): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(592): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/foinfo/pasalibros.foinfo.cloud/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/foinfo/pasalibros.foinfo.cloud/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 253
